<#
.SYNOPSIS
    Set up this Windows machine as a control terminal for the claudefarm
    Claude instances running on K12 (or any machine running claude-mgr).

.DESCRIPTION
    Idempotent client setup. Does NOT install claude-mgr or run instances
    locally - just clones the alias repo, wires up SSH, copies your pubkey
    to the server, and tests the connection.

    Re-run any time - it skips work that's already done.

.PARAMETER RepoPath
    Where to clone (or update) the claudefarm repo. Default: %USERPROFILE%\github\claudefarm

.PARAMETER ServerHost
    LAN IP / hostname of the claudefarm server you want to attach to.
    Default: 192.168.50.62 (K12)

.PARAMETER ServerUser
    SSH user on the server. Default: root

.EXAMPLE
    iwr -useb https://raw.githubusercontent.com/Clinteastman/claudefarm/main/client/setup-client.ps1 | iex

.EXAMPLE
    .\setup-client.ps1 -ServerHost 10.0.0.5 -ServerUser pi
#>
[CmdletBinding()]
param(
    [string]$RepoPath  = "$env:USERPROFILE\github\claudefarm",
    [string]$ServerHost = "192.168.50.62",
    [string]$ServerUser = "root"
)

$ErrorActionPreference = "Stop"

# ---- Catppuccin Mocha colours via ANSI ------------------------------------
$ESC   = [char]27
$M     = "$ESC[38;2;203;166;247m"   # mauve
$G     = "$ESC[38;2;166;227;161m"   # green
$Y     = "$ESC[38;2;249;226;175m"   # yellow
$R     = "$ESC[38;2;243;139;168m"   # red
$S     = "$ESC[38;2;108;112;134m"   # overlay
$Cs    = "$ESC[38;2;116;199;236m"   # sapphire
$B     = "$ESC[1m"
$N     = "$ESC[0m"

function Step($msg) { Write-Host ""; Write-Host "$M$B==>$N $B$msg$N" }
function Info($msg) { Write-Host "    $S$msg$N" }
function Ok($msg)   { Write-Host "    $G  OK$N  $S$msg$N" }
function Skip($msg) { Write-Host "    $S  --$N  $S$msg (already done)$N" }
function Warn($msg) { Write-Host "    $Y  !!$N  $Y$msg$N" }
function Fail($msg) { Write-Host "    $R  xx$N  $R$msg$N"; exit 1 }

# ---- preflight -----------------------------------------------------------

Step "preflight"
if ($PSVersionTable.PSVersion.Major -lt 5) {
    Fail "PowerShell 5+ required (found $($PSVersionTable.PSVersion))"
}
Ok "running PowerShell $($PSVersionTable.PSVersion)"

foreach ($tool in @("git", "ssh", "ssh-keygen")) {
    if (-not (Get-Command $tool -ErrorAction SilentlyContinue)) {
        Fail "$tool not found - install Git for Windows + OpenSSH first (winget install Git.Git Microsoft.OpenSSH.Beta)"
    }
}
Ok "git, ssh, ssh-keygen present"

# ---- repo ----------------------------------------------------------------

Step "claudefarm repo at $RepoPath"
if (Test-Path "$RepoPath\.git") {
    Info "existing clone found, pulling latest"
    git -C $RepoPath pull --ff-only --quiet 2>&1 | ForEach-Object { Info $_ }
    Ok "$RepoPath up to date"
} else {
    Info "cloning to $RepoPath"
    New-Item -ItemType Directory -Force -Path (Split-Path $RepoPath) | Out-Null
    git clone --quiet https://github.com/Clinteastman/claudefarm.git $RepoPath
    Ok "cloned"
}

# Convert Windows path to forward-slash form for SSH config
$AliasGlob = $RepoPath.Replace("\", "/") + "/client/claude-instances-*.cfg"

# ---- ssh key -------------------------------------------------------------

Step "ssh key"
$SshDir = "$env:USERPROFILE\.ssh"
if (-not (Test-Path $SshDir)) {
    New-Item -ItemType Directory -Path $SshDir | Out-Null
}

$Pubkey = $null
foreach ($cand in @("$SshDir\id_ed25519.pub", "$SshDir\id_rsa.pub", "$SshDir\id_ecdsa.pub")) {
    if (Test-Path $cand) {
        $Pubkey = $cand
        break
    }
}

if (-not $Pubkey) {
    Warn "no SSH key found in $SshDir"
    $ans = Read-Host "    $Cs?$N Generate one now (ed25519, no passphrase)? [Y/n]"
    if ($ans -notmatch "^[nN]") {
        ssh-keygen -t ed25519 -f "$SshDir\id_ed25519" -N '' -C "$env:USERNAME@$env:COMPUTERNAME" | Out-Null
        $Pubkey = "$SshDir\id_ed25519.pub"
        Ok "generated $Pubkey"
    } else {
        Fail "no key, no SSH access - re-run when you've generated one"
    }
} else {
    Ok "found $Pubkey"
}

# ---- ssh config Include --------------------------------------------------

Step "%USERPROFILE%\.ssh\config Include"
$SshCfg = "$SshDir\config"
$IncludeLine = "Include $AliasGlob"
$Header = "# claudefarm: SSH aliases auto-generated by claude-mgr on each server.
# This Include MUST be at the top of the file, before any Host blocks."

if ((Test-Path $SshCfg) -and ((Get-Content $SshCfg -Raw) -match [regex]::Escape($IncludeLine))) {
    Skip "Include line already present"
} elseif ((Test-Path $SshCfg) -and ((Get-Content $SshCfg -Raw) -match "(?m)^\s*Include\s.*claude-instances")) {
    Warn "an old/different claude-instances Include is already in $SshCfg"
    Info "edit it to:  $IncludeLine"
} else {
    if (Test-Path $SshCfg) {
        $bk = "$SshCfg.pre-claudefarm-$(Get-Date -Format yyyyMMddHHmmss).bak"
        Copy-Item $SshCfg $bk
        Info "backed up $SshCfg to $bk"
        $existing = Get-Content $SshCfg -Raw
        Set-Content $SshCfg -Value "$Header`n$IncludeLine`n`n$existing" -NoNewline
    } else {
        Set-Content $SshCfg -Value "$Header`n$IncludeLine`n"
    }
    Ok "added Include line to top of $SshCfg"
}

# ---- copy pubkey to server ----------------------------------------------

Step "authorise this machine on $ServerUser@$ServerHost"
Write-Host "    $S Your public key (paste this onto the server if needed):$N"
Write-Host ""
Write-Host "    $Cs"
Get-Content $Pubkey | ForEach-Object { Write-Host "    $_" }
Write-Host "$N"

$ans = Read-Host "    $Cs?$N Try to copy this key to ${ServerUser}@${ServerHost} now? [Y/n]"
if ($ans -notmatch "^[nN]") {
    # Windows OpenSSH doesn't ship ssh-copy-id - do it via stdin | ssh. Stream
    # the key over stdin and have the remote read it with $(cat), so a quote or
    # metacharacter in the key comment can't break out of the remote command.
    $pubContent = (Get-Content $Pubkey -Raw).Trim()
    $remoteCmd  = 'umask 077; mkdir -p ~/.ssh; k=$(cat); grep -qxF "$k" ~/.ssh/authorized_keys 2>/dev/null || printf "%s\n" "$k" >> ~/.ssh/authorized_keys'
    try {
        $pubContent | ssh "${ServerUser}@${ServerHost}" $remoteCmd
        Ok "pubkey installed on $ServerHost"
    } catch {
        Warn "could not install via ssh - paste the key above into ~/.ssh/authorized_keys on $ServerHost manually"
    }
}

# ---- test connection ----------------------------------------------------

Step "test connection"
$ans = Read-Host "    $Cs?$N Try ssh ${ServerUser}@${ServerHost} hostname now? [Y/n]"
if ($ans -notmatch "^[nN]") {
    try {
        $hostname = ssh -o BatchMode=yes -o ConnectTimeout=5 "${ServerUser}@${ServerHost}" hostname
        Ok "ssh works (server: $hostname)"
    } catch {
        Warn "ssh failed - check key install + LAN reachability"
    }
}

# ---- done ---------------------------------------------------------------

Step "done"
Write-Host ""
Write-Host "  $G$B This client is ready.$N"
Write-Host ""
Write-Host "  Try one of these (auto-generated from servers' running instances):"
Write-Host ""

Get-ChildItem "$RepoPath\client\claude-instances-*.cfg" -ErrorAction SilentlyContinue | ForEach-Object {
    Get-Content $_ | Where-Object { $_ -match "^Host claude-" } | ForEach-Object {
        $name = $_.Trim() -replace "^Host\s+", ""
        Write-Host "    $Cs ssh $name $N"
    }
}
Write-Host ""
Write-Host "  $S Pull the repo ($RepoPath) any time to refresh aliases when servers"
Write-Host "  spin up new instances:  git -C $RepoPath pull$N"
Write-Host ""
